# Basic
title: Muller
subtitle: Muller's Blog
welcome_message: Hello Friend.
description: 贾柯的博客记录.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://github.com/mullertosuccess"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://github.com/mullertosuccess'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: _被风追的少年
    github: MullerToSuccess
    gplus: 107108267983477358170
    mail: greatpage1@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
