safe: false
permalink: /2016/:title.html
exclude:
  - README.md

name: Muller's Blog
host: localhost
desc: Life is flood current,no one can resist it.

custom:
    category:
        Javascript: Javascript
        Css: Css
        Node: Node
        Vue: Vue
        随笔: 随笔
        诗: 诗
    categories:
      - name:  Javascript
        title: Javascript

      - name:  Css
        title: Css 
        
      - name:  Node
        title: Node 
        
      - name:  Vue
        title: Vue        
        
      - name:  随笔
        title: 随笔 
        
      - name:  诗
        title: 诗 

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Muller
        email: Greatpage1@gmail.com
        disqus: your-disqus-short-name              # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: MullerToSuccess                     # GitHub账号
        gravatar: 11567575b6e78a542c16ac561ff2d0b9 

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
